namespace LaneZstd.Core;

public enum RuntimeCounter
{
    SessionsCreated,
    SessionsClosed,
    SessionsTimedOut,
    EdgePacketsIn,
    EdgePacketsOut,
    HubPacketsIn,
    HubPacketsOut,
    GamePacketsIn,
    GamePacketsOut,
    RawFramesOut,
    CompressedFramesOut,
    RawBytesIn,
    FramedBytesOut,
    OversizeDrop,
    ProtocolError,
    DecompressError,
    EncodeOperations,
    EncodeElapsedTicks,
    DecodeOperations,
    DecodeElapsedTicks,
    QueueEnqueued,
    QueueDequeued,
    QueueDropped,
    QueueCompleted,
    UnknownSession,
    SessionSenderMismatch,
    PortPoolExhausted,
}
